batch_size: 2 #512
epochs: 100
eval_every_n_epochs: 1
fine_tune_from: None
log_every_n_steps: 2
weight_decay: 10e-6
fp16_precision: False

model:
  out_dim: 2  #previously 256 .. now changing to two
  base_model: "grayresnet"

dataset:
  s: 1
  input_shape: (96,96,3)
  num_workers: 0
  valid_size: 0.05

loss:
  temperature: 0.5
  use_cosine_similarity: True
